name: Build and Push Images

on:
  # Manual trigger only - always builds from dev branch
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag (default latest)"
        required: false
        default: "latest"

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Always checkout dev branch
          ref: dev

      - name: Set up Node (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Set up Node (backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: server
        run: npm ci

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set image tag
        id: vars
        run: |
          # Use input tag or default to 'latest'
          IMAGE_TAG="${{ github.event.inputs.image_tag || 'latest' }}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Building images from dev branch with tag: ${IMAGE_TAG}"

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/linoymalakkaran/play-learn-spark-frontend:${{ steps.vars.outputs.IMAGE_TAG }} -f client/Dockerfile client
          
      - name: Build backend image
        run: |
          docker build -t ghcr.io/linoymalakkaran/play-learn-spark-backend:${{ steps.vars.outputs.IMAGE_TAG }} -f server/Dockerfile server

      - name: Push images
        run: |
          docker push ghcr.io/linoymalakkaran/play-learn-spark-frontend:${{ steps.vars.outputs.IMAGE_TAG }}
          docker push ghcr.io/linoymalakkaran/play-learn-spark-backend:${{ steps.vars.outputs.IMAGE_TAG }}
