name: Build and Push Images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from (dev/prod)"
        required: true
        default: "dev"
      image_tag:
        description: "Image tag (default latest)"
        required: false
        default: "latest"
  push:
    branches: [ dev ]
    paths:
      - 'client/**'
      - 'server/**'
      - 'Dockerfile*'
      - 'docker-compose*.yml'

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'dev' }}

      - name: Set up Node (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Set up Node (backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install backend deps
        working-directory: server
        run: npm ci

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build frontend image
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker build -t ghcr.io/linoymalakkaran/play-learn-spark-frontend:${IMAGE_TAG} -f client/Dockerfile client
      - name: Build backend image
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker build -t ghcr.io/linoymalakkaran/play-learn-spark-backend:${IMAGE_TAG} -f server/Dockerfile server

      - name: Push images
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker push ghcr.io/linoymalakkaran/play-learn-spark-frontend:${IMAGE_TAG}
          docker push ghcr.io/linoymalakkaran/play-learn-spark-backend:${IMAGE_TAG}
