name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Lengths
        run: |
          echo "MONGODB_ATLAS_URI length: ${#MONGODB_ATLAS_URI}"
          echo "JWT_SECRET length: ${#JWT_SECRET}" 
          echo "GOOGLE_AI_API_KEY length: ${#GOOGLE_AI_API_KEY}"
          echo "MONGODB_ATLAS_URI starts with: ${MONGODB_ATLAS_URI:0:10}..."
          echo "JWT_SECRET starts with: ${JWT_SECRET:0:5}..."
          echo "GOOGLE_AI_API_KEY starts with: ${GOOGLE_AI_API_KEY:0:10}..."
        env:
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}