name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Lengths and Presence
        run: |
          echo "=== CHECKING SECRET PRESENCE ==="
          echo "MONGODB_ATLAS_URI length: ${#MONGODB_ATLAS_URI}"
          echo "JWT_SECRET length: ${#JWT_SECRET}" 
          echo "GOOGLE_AI_API_KEY length: ${#GOOGLE_AI_API_KEY}"
          echo ""
          echo "=== CHECKING IF SECRETS ARE EMPTY ==="
          if [ -z "$MONGODB_ATLAS_URI" ]; then
            echo "❌ MONGODB_ATLAS_URI is EMPTY"
          else
            echo "✅ MONGODB_ATLAS_URI has content (${#MONGODB_ATLAS_URI} chars)"
            echo "   Starts with: ${MONGODB_ATLAS_URI:0:15}..."
          fi
          
          if [ -z "$JWT_SECRET" ]; then
            echo "❌ JWT_SECRET is EMPTY"
          else
            echo "✅ JWT_SECRET has content (${#JWT_SECRET} chars)"
            echo "   Starts with: ${JWT_SECRET:0:8}..."
          fi
          
          if [ -z "$GOOGLE_AI_API_KEY" ]; then
            echo "❌ GOOGLE_AI_API_KEY is EMPTY"
          else
            echo "✅ GOOGLE_AI_API_KEY has content (${#GOOGLE_AI_API_KEY} chars)"
            echo "   Starts with: ${GOOGLE_AI_API_KEY:0:10}..."
          fi
        env:
          MONGODB_ATLAS_URI: ${{ secrets.MONGODB_ATLAS_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}